runtime: python311
# EITHER remove entrypoint (recommended for Standard) ...
# entrypoint: gunicorn -b :$PORT app:app   # <- keep ONLY if you also add gunicorn to requirements.txt

handlers:
# Serve the homepage at /
- url: /
  static_files: events.html
  upload: events.html

# Serve other static assets in the root (css/js/images)
- url: /(.*\.(css|js|png|jpg|jpeg|gif|ico))
  static_files: \1
  upload: (.*\.(css|js|png|jpg|jpeg|gif|ico))

# All other routes go to your Flask app in app.py
- url: /.*
  script: auto