runtime: nodejs18

# Environment variables (you should set these in Google Cloud Console instead for security)
env_variables:
  NODE_ENV: "production"
  # DO NOT commit actual API keys here - set them in GCP Console instead
  # TICKETMASTER_API_KEY: "your_key_here"
  # SPOTIFY_CLIENT_ID: "your_id_here"
  # SPOTIFY_CLIENT_SECRET: "your_secret_here"
  # MONGODB_URI: "your_mongodb_uri_here"

# Handlers
handlers:
  # Serve static files from the dist directory
  - url: /assets
    static_dir: dist/assets
    secure: always

  - url: /robots.txt
    static_files: dist/robots.txt
    upload: dist/robots.txt
    secure: always

  # API routes handled by Node.js
  - url: /api/.*
    script: auto
    secure: always

  # All other routes serve the React app
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
