runtime: nodejs20

# Environment variables (you should set these in Google Cloud Console instead for security)
env_variables:
  NODE_ENV: "production"
  # DO NOT commit actual API keys here - set them in GCP Console instead
  TICKETMASTER_API_KEY: 'w71ehIlQymxGnc42SoC5Mw7AXg2eKACY'
  SPOTIFY_CLIENT_ID: '78741ea495f94ba08ebe67a8ce5e9e6c'
  SPOTIFY_CLIENT_SECRET: 'bfb6e178c8ed4231aead9fe985db786d'
  MONGODB_URI: 'mongodb://kxhancoc_db_user:mqNEC2PB6fnnOXx3@ac-cyhxmm6-shard-00-00.p8idqfz.mongodb.net:27017,ac-cyhxmm6-shard-00-01.p8idqfz.mongodb.net:27017,ac-cyhxmm6-shard-00-02.p8idqfz.mongodb.net:27017/hw3?ssl=true&authSource=admin&retryWrites=true&w=majority'
  PORT: '8080'

# Handlers
handlers:
  # Serve static assets (must be before catch-all)
  - url: /assets
    static_dir: backend/public/assets
    secure: always

  - url: /robots.txt
    static_files: backend/public/robots.txt
    upload: backend/public/robots.txt
    secure: always

  - url: /placeholder.svg
    static_files: backend/public/placeholder.svg
    upload: backend/public/placeholder.svg
    secure: always

  - url: /favicon.ico
    static_files: backend/public/favicon.ico
    upload: backend/public/favicon.ico
    secure: always
    expiration: "1d"

  # API routes handled by Node.js
  - url: /api/.*
    script: auto
    secure: always

  # All other routes serve the React app (must be last)
  - url: /.*
    script: auto
    secure: always

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
