runtime: nodejs18
env: standard

env_variables:
  TICKETMASTER_API_KEY: "YOUR_API_KEY"
  SPOTIFY_CLIENT_ID: "YOUR_SPOTIFY_ID"
  SPOTIFY_CLIENT_SECRET: "YOUR_SPOTIFY_SECRET"
  MONGODB_URI: "YOUR_MONGODB_CONNECTION_STRING"
